// ESLint (flat config) for the web app. Pragmatic ruleset: real-bug rules stay as errors; stylistic
// or intentionally-idiomatic patterns in this codebase are warnings or off, so `npm run lint` is a
// useful signal (dead code, unreachable, bad awaits) without drowning in noise. Type-unaware for speed.
import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";

export default tseslint.config(
  { ignores: ["dist/**", "node_modules/**", "src-tauri/**", "public/**", "scripts/**", "*.config.js",
              "src/api/schema.d.ts"] },   // generated by openapi-typescript
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    // Type-aware linting (T6) — enabled ONLY so `no-floating-promises` / `no-misused-promises` can see
    // types. We deliberately do NOT switch to `recommendedTypeChecked` (it would flood on the `any` used
    // at the IFC/three/@thatopen boundaries); we opt in to just the two promise-safety rules below.
    languageOptions: {
      globals: { ...globals.browser, ...globals.node, ...globals.worker },
      parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname },
    },
    rules: {
      // Unhandled promises swallow errors and cause out-of-order writes; require await/void/.catch.
      "@typescript-eslint/no-floating-promises": "error",
      // Catch genuinely-dangerous promise misuse (a Promise used as a condition, or spread) — but NOT
      // async event handlers (`el.onclick = async …`), which are idiomatic here and safe (the browser
      // discards the return); flagging ~90 of them would be churn, not a real defect fix.
      "@typescript-eslint/no-misused-promises": ["error", { checksVoidReturn: false }],
      // this codebase deliberately uses `any` at IFC/three/@thatopen boundaries and compact idioms;
      // keep the linter focused on genuine defects, not style it intentionally adopts.
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
      // legitimate closure capture: object-literal getters can't reference `this` (const self = this).
      "@typescript-eslint/no-this-alias": "off",
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_",
                                                       caughtErrorsIgnorePattern: "^_" }],
      "@typescript-eslint/no-empty-function": "off",
      "@typescript-eslint/ban-ts-comment": "warn",
      "no-empty": ["warn", { allowEmptyCatch: true }],
      "prefer-const": "warn",
      "no-constant-condition": ["error", { checkLoops: false }],
    },
  },
  { files: ["**/*.test.ts"], rules: { "@typescript-eslint/no-unused-expressions": "off" } },
);
