// ESLint (flat config) for the web app. Pragmatic ruleset: real-bug rules stay as errors; stylistic
// or intentionally-idiomatic patterns in this codebase are warnings or off, so `npm run lint` is a
// useful signal (dead code, unreachable, bad awaits) without drowning in noise. Type-unaware for speed.
import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";

export default tseslint.config(
  // NOTE `scripts/**` is deliberately NOT ignored — see the block at the bottom of this file.
  { ignores: ["dist/**", "node_modules/**", "src-tauri/**", "public/**", "*.config.js",
              "src/api/schema.d.ts",      // generated by openapi-typescript
              // Vendored verbatim from MassingCloud/massingifc (MIT) — see src/vendor/massingifc/VENDOR.md.
              // Third-party source is not ours to restyle: linting it by our rules would either force a
              // fork or bury real findings in someone else's house style, and every deviation makes the
              // next re-sync a merge instead of a copy. It IS typechecked (tsc) and RUN (vitest).
              "src/vendor/**"] },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    // Type-aware linting (T6) — enabled ONLY so `no-floating-promises` / `no-misused-promises` can see
    // types. We deliberately do NOT switch to `recommendedTypeChecked` (it would flood on the `any` used
    // at the IFC/three/@thatopen boundaries); we opt in to just the two promise-safety rules below.
    languageOptions: {
      globals: { ...globals.browser, ...globals.node, ...globals.worker },
      parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname },
    },
    rules: {
      // Unhandled promises swallow errors and cause out-of-order writes; require await/void/.catch.
      "@typescript-eslint/no-floating-promises": "error",
      // Catch genuinely-dangerous promise misuse (a Promise used as a condition, or spread) — but NOT
      // async event handlers (`el.onclick = async …`), which are idiomatic here and safe (the browser
      // discards the return); flagging ~90 of them would be churn, not a real defect fix.
      "@typescript-eslint/no-misused-promises": ["error", { checksVoidReturn: false }],
      // this codebase deliberately uses `any` at IFC/three/@thatopen boundaries and compact idioms;
      // keep the linter focused on genuine defects, not style it intentionally adopts.
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
      // legitimate closure capture: object-literal getters can't reference `this` (const self = this).
      "@typescript-eslint/no-this-alias": "off",
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_",
                                                       caughtErrorsIgnorePattern: "^_" }],
      "@typescript-eslint/no-empty-function": "off",
      "@typescript-eslint/ban-ts-comment": "warn",
      "no-empty": ["warn", { allowEmptyCatch: true }],
      "prefer-const": "warn",
      // A value written and then provably overwritten before any read. Enabled 2026-08-07 after it
      // found 14 of them — every one the same shape: `let x = <default>;` immediately followed by a
      // `try { x = await … } catch { …; return; }`, where the catch returns and the default is
      // therefore never observed. Harmless individually, but each one is a lie about the code's
      // states: it claims a fallback exists on a path that cannot reach it, so a reader reasoning
      // about "what if the load fails" gets the wrong answer. `tsc --noEmit` accepts every site with
      // the initializer removed, which is the independent confirmation that they were unreachable.
      // "error", not "warn": the whole point is that it cannot silently accumulate again.
      "no-useless-assignment": "error",
      // The other two rules `@eslint/js` 10 adds to `recommended`, adopted here so the dependency
      // bump (#236) carries no behaviour change with it. The full delta 9.39.5 -> 10.0.1 is exactly
      // three added rules and none removed: the one above, plus these. Both measure **0 findings**
      // across `src/**/*.ts`, `scripts/**/*.mjs` and `capacitor.config.ts`.
      //
      // A zero is the result least worth trusting, so both were mutation-checked: a planted
      // never-assigned `let` and a planted `catch (e) { throw new Error(...) }` are each reported.
      // The rules are armed and the codebase genuinely has none — as opposed to a flag that quietly
      // did nothing, which reads identically in the output.
      //
      // Worth recording why the bump was low-risk: the ESLint **engine** is already 10.8.0, so
      // v10's breaking changes are live today. `@eslint/js` only supplies `configs.recommended`, so
      // #236 moves which rules that preset turns on and nothing else.
      "no-unassigned-vars": "error",
      "preserve-caught-error": "error",
      "no-constant-condition": ["error", { checkLoops: false }],
    },
  },
  { files: ["**/*.test.ts"], rules: { "@typescript-eslint/no-unused-expressions": "off" } },

  /**
   * `scripts/` — the Node build tooling — was in `ignores` until 2026-08-06, so **the only web source
   * nobody linted was the source that gates the build**: `check-vite-version.mjs` (refuses a build on
   * the wrong Vite), `check-licences.mjs` (the licence allowlist), `bundle-budget.mjs` (the shell
   * budget and the vendor split), `copy-wasm.mjs` and `wasmSources.mjs`.
   *
   * That mattered concretely. `eslint`'s `no-misleading-character-class` — on by default via
   * `js.configs.recommended` — caught a real bug in `src/shell/roadmapSelfConsistent.test.ts`
   * (`[◧🟡]`, where 🟡 is U+1F7E1 and a non-`u` class splits the surrogate pair). Had the same
   * mistake been made one directory over in `scripts/`, nothing would have said a word.
   *
   * Type-aware parsing is turned OFF here rather than the files added to `tsconfig.json`. These are
   * standalone Node programs run by `node scripts/x.mjs`, not part of the app's compilation unit;
   * pulling them into the project service just to lint them would make `tsc --noEmit` responsible for
   * build tooling it never emits. Without this block the run does not merely skip them — it errors
   * with "was not found by the project service", which is why the directory was ignored in the first
   * place rather than a decision anyone made about linting build scripts.
   */
  {
    files: ["scripts/**/*.mjs", "scripts/**/*.js"],
    languageOptions: {
      globals: { ...globals.node },
      parserOptions: { projectService: false, project: false },
    },
    rules: {
      // The promise-safety pair needs types; they are unavailable here by design (above).
      "@typescript-eslint/no-floating-promises": "off",
      "@typescript-eslint/no-misused-promises": "off",
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "@typescript-eslint/no-unused-vars": "off",   // the base rule covers plain .mjs
    },
  },
);
