"""R31-SCHEMA-DIAG — structural IFC diagnostics.

Two things this file must prove, and the first is the one that decides whether the engine is usable:

1. **A valid file comes back clean.** A structural validator with false positives is worse than none —
   it trains people to ignore it, and then it is present but not read. So real sample IFCs the platform
   ships are asserted at **zero** errors, not "few".
2. **Each check actually fires.** Every code is exercised by a file broken in exactly that one way,
   because a check that cannot fire is indistinguishable from a check that passes.

The known-good files are deliberately **not** generated by this test. Round-tripping through my own
writer would prove my writer and my reader agree, which is the failure mode described in
`assert-against-a-reader-you-did-not-write`: it passes on the wrong format. These are files produced by
other tools and by the platform's ifcopenshell path.
"""
from __future__ import annotations

import gc
import os
from shutil import rmtree as shutil_rmtree

from aec_data import schema_diag as SD

SAMPLES = os.path.join(os.path.dirname(__file__), "..", "..", "samples")

#: Small, valid, non-2X3 samples. The two 51 MB IFC2X3 houses are excluded for runtime (38 s each),
#: not because they pass — they do not, and `test_real_violation_in_a_shipped_sample` is about that.
CLEAN = ["earth_dome.ifc", "maple_tower.ifc", "rooms_demo.ifc", "school_mep.ifc", "vertical_farm.ifc"]

MINIMAL = """ISO-10303-21;
HEADER;
FILE_DESCRIPTION((''),'2;1');
FILE_NAME('t','2026-07-30T00:00:00',(''),(''),'','','');
FILE_SCHEMA(('IFC4'));
ENDSEC;
DATA;
#1= IFCPROJECT('0000000000000000000001',$,'P',$,$,$,$,$,$);
#2= IFCCARTESIANPOINT((0.,0.,0.));
ENDSEC;
END-ISO-10303-21;
"""


def _codes(text: str) -> dict[str, int]:
    return SD.diagnose_text(text)["summary"]["by_code"]


def test_minimal_valid_file_is_clean():
    r = SD.diagnose_text(MINIMAL)
    assert r["checked_schema"] == "IFC4"
    assert r["instances"] == 2
    assert r["summary"]["error"] == 0, r["findings"]
    assert r["passed"] is True


def test_a_real_ifc_from_an_independent_writer_is_clean():
    """The no-false-positives gate, and the one that runs EVERYWHERE.

    `ifcopenshell` writes the file; this module reads it as text with its own parser. Those are
    entirely separate implementations, so this is not the round-trip-through-my-own-writer trap — the
    producer is a reader I did not write, which is exactly the property
    `assert-against-a-reader-you-did-not-write` asks for.

    This exists because the shipped `samples/*.ifc` are **gitignored** (`.gitignore:52 samples/*`), so
    they are present on a dev machine and absent on CI. The first version of this file asserted
    `checked >= 4` against them and **failed the API gate on `main`** — a fixture-dependent test that
    passed locally for the same reason it failed remotely.
    """
    import tempfile

    import ifcopenshell

    m = ifcopenshell.file(schema="IFC4")
    proj = m.create_entity("IfcProject", GlobalId=ifcopenshell.guid.new(), Name="P")
    origin = m.create_entity("IfcCartesianPoint", Coordinates=(0.0, 0.0, 0.0))
    axes = m.create_entity("IfcAxis2Placement3D", Location=origin)
    # `WorldCoordinateSystem` is mandatory. The first draft of this fixture omitted it and the engine
    # correctly flagged it — the fixture was invalid, not the check. Left as a comment because it is
    # the cheapest possible demonstration that this test can fail.
    ctx = m.create_entity("IfcGeometricRepresentationContext",
                          CoordinateSpaceDimension=3, WorldCoordinateSystem=axes)
    proj.RepresentationContexts = [ctx]
    site = m.create_entity("IfcSite", GlobalId=ifcopenshell.guid.new(), Name="S")
    bldg = m.create_entity("IfcBuilding", GlobalId=ifcopenshell.guid.new(), Name="B")
    storey = m.create_entity("IfcBuildingStorey", GlobalId=ifcopenshell.guid.new(), Name="L1")
    for parent, child in ((proj, site), (site, bldg), (bldg, storey)):
        m.create_entity("IfcRelAggregates", GlobalId=ifcopenshell.guid.new(),
                        RelatingObject=parent, RelatedObjects=[child])
    for i in range(12):
        m.create_entity("IfcWall", GlobalId=ifcopenshell.guid.new(), Name=f"W{i}")

    d = tempfile.mkdtemp()
    try:
        path = os.path.join(d, "generated.ifc")
        m.write(path)
        r = SD.diagnose_file(path)
        assert r["instances"] > 10, f"only {r['instances']} instances parsed from a written IFC"
        assert r["summary"]["error"] == 0, f"false positives on a valid file: {r['summary']['by_code']} {r['findings'][:3]}"
    finally:
        shutil_rmtree(d)


def test_shipped_samples_have_zero_structural_errors():
    """The same property against real third-party models — OPPORTUNISTIC, because they are gitignored.

    `samples/*.ifc` are not in version control, so this checks several real models on a dev machine and
    honestly reports that it checked nothing on CI. It does **not** assert a minimum count: that is what
    broke the API gate. The vacuous-loop risk it was guarding against is covered instead by
    `test_a_real_ifc_from_an_independent_writer_is_clean`, which has a fixture it creates itself and so
    cannot silently check zero files.
    """
    checked = 0
    for name in CLEAN:
        p = os.path.join(SAMPLES, name)
        if not os.path.exists(p):
            continue
        checked += 1
        r = SD.diagnose_file(p)
        assert r["summary"]["error"] == 0, f"{name}: {r['summary']['by_code']} {r['findings'][:3]}"
        assert r["instances"] > 10, f"{name}: only {r['instances']} instances — did the scan find the DATA section?"
        del r
        gc.collect()
    if checked == 0:
        print("      (no sample IFCs on disk — gitignored; the generated-IFC test carries this property)")


def test_real_violation_in_a_shipped_sample():
    """`basichouse.ifc` really does violate IFC2X3 — a mainstream exporter wrote a non-conforming file.

    `IfcFurnitureType.AssemblyPlace` is declared mandatory (`optional=False`) in both IFC2X3 and IFC4,
    and 27 instances in that file pass `$`. The file loads, renders and passes IDS. That is the whole
    argument for this engine: rule compliance and structural validity are different questions.

    Asserted as a floor and by code — not as `== 27` — because the assertion that matters is "this
    class of defect is detected in a real file", and pinning the exact count would make a sample-file
    refresh look like a regression.
    """
    p = os.path.join(SAMPLES, "basichouse.ifc")
    if not os.path.exists(p):
        return
    r = SD.diagnose_file(p)
    try:
        assert r["checked_schema"] == "IFC2X3"
        assert r["summary"]["by_code"].get("MISSING_REQUIRED", 0) >= 20
        # No other ERROR code: another one here would mean false positives at scale. Asserted over
        # errors rather than over every code, because a *warning* is allowed and expected — this model
        # has over 400 k distinct references, so `REFS_NOT_FULLY_CHECKED` fires. The first version of
        # this line demanded the whole by_code set be `{MISSING_REQUIRED}` and broke the moment the cap
        # started announcing itself, which is the assertion conflating "clean" with "silent".
        errs = {c for c in r["summary"]["by_code"] if SD._SEVERITY.get(c, "error") == "error"}
        assert errs == {"MISSING_REQUIRED"}, r["summary"]["by_code"]
        assert r["summary"]["by_code"].get("REFS_NOT_FULLY_CHECKED") == 1, (
            "the reference cap must SAY it truncated; silence here would read as no dangling refs")
    finally:
        # This is the only test that reads a 51 MB model, and the suite runs every test in ONE process.
        # Holding the string plus the reference map into the next test is what produced a MemoryError
        # that failed `test_clash_xml_import` and `test_cbs` — tests with no connection to this file.
        del r
        gc.collect()


# --- one file broken in exactly one way, per check ------------------------------------------------

def test_unknown_entity():
    t = MINIMAL.replace("#2= IFCCARTESIANPOINT((0.,0.,0.));", "#2= IFCNOTATHING('x');")
    assert _codes(t).get("UNKNOWN_ENTITY") == 1


def test_abstract_entity_cannot_be_instantiated():
    # IfcProduct is ABSTRACT: legal as a supertype, illegal as an instance. ifcopenshell will happily
    # read this, which is exactly why a reader-based check would miss it.
    t = MINIMAL.replace("#2= IFCCARTESIANPOINT((0.,0.,0.));", "#2= IFCPRODUCT('0000000000000000000002',$,$,$,$,$,$);")
    assert _codes(t).get("ABSTRACT_ENTITY") == 1


def test_type_used_as_a_top_level_instance():
    # A defined type is legal INSIDE an attribute and illegal as an instance — a different fault from
    # a name that is simply absent, and reported as a different code so the fix differs too.
    t = MINIMAL.replace("#2= IFCCARTESIANPOINT((0.,0.,0.));", "#2= IFCLENGTHMEASURE(1.);")
    assert _codes(t).get("NOT_AN_ENTITY") == 1


def test_dangling_reference():
    t = MINIMAL.replace("#2= IFCCARTESIANPOINT((0.,0.,0.));",
                        "#2= IFCSITE('0000000000000000000002',$,$,$,$,#9999,$,$,$,$,$,$,$,$);")
    assert _codes(t).get("DANGLING_REF") == 1


def test_duplicate_instance_id():
    t = MINIMAL.replace("#2= IFCCARTESIANPOINT((0.,0.,0.));",
                        "#2= IFCCARTESIANPOINT((0.,0.,0.));\n#2= IFCCARTESIANPOINT((1.,1.,1.));")
    assert _codes(t).get("DUPLICATE_ID") == 1


def test_attribute_count_mismatch():
    t = MINIMAL.replace("#1= IFCPROJECT('0000000000000000000001',$,'P',$,$,$,$,$,$);",
                        "#1= IFCPROJECT('0000000000000000000001',$,'P');")
    assert _codes(t).get("ATTR_COUNT") == 1


def test_missing_mandatory_attribute():
    # IfcProject.GlobalId is mandatory; $ in slot 0 is a structural violation, not a blank name.
    t = MINIMAL.replace("#1= IFCPROJECT('0000000000000000000001',$,'P',$,$,$,$,$,$);",
                        "#1= IFCPROJECT($,$,'P',$,$,$,$,$,$);")
    assert _codes(t).get("MISSING_REQUIRED") == 1


def test_derived_marker_where_nothing_is_derived():
    t = MINIMAL.replace("#1= IFCPROJECT('0000000000000000000001',$,'P',$,$,$,$,$,$);",
                        "#1= IFCPROJECT('0000000000000000000001',$,*,$,$,$,$,$,$);")
    assert _codes(t).get("UNEXPECTED_DERIVED") == 1


def test_unsupported_schema_is_reported_not_guessed():
    """The honest-failure case: an unknown schema must NOT fall back to a similar one.

    Silently checking an IFC9 file against IFC4 would produce a page of confident, wrong findings —
    the `confident-wrong-beats-missing` shape. It reports that it cannot check, and says so in the
    message rather than returning `passed: True`.
    """
    t = MINIMAL.replace("FILE_SCHEMA(('IFC4'));", "FILE_SCHEMA(('IFC9'));")
    r = SD.diagnose_text(t)
    assert r["checked_schema"] is None
    assert r["passed"] is False
    assert "SCHEMA_UNSUPPORTED" in r["summary"]["by_code"]
    assert "does NOT mean the file is valid" in r["findings"][0]["message"]


def test_no_instances_is_an_error_not_a_pass():
    # An empty DATA section must not read as "nothing wrong with this file".
    t = MINIMAL.replace("#1= IFCPROJECT('0000000000000000000001',$,'P',$,$,$,$,$,$);\n", "") \
               .replace("#2= IFCCARTESIANPOINT((0.,0.,0.));\n", "")
    r = SD.diagnose_text(t)
    assert r["passed"] is False
    assert "NO_INSTANCES" in r["summary"]["by_code"]


def test_schema_normalisation_prefers_the_longest_match():
    # IFC4X3 must not resolve to IFC4: checking against the wrong schema is worse than not checking,
    # because it produces findings that look authoritative.
    assert SD.normalise_schema("IFC4X3_ADD2") == "IFC4X3_ADD2"
    assert SD.normalise_schema("IFC4X3") == "IFC4X3"
    assert SD.normalise_schema("IFC4") == "IFC4"
    assert SD.normalise_schema("IFC2X3") == "IFC2X3"
    assert SD.normalise_schema("IFC9") is None
    assert SD.normalise_schema(None) is None


# --- the splitter, which is where a hand-rolled parser normally goes wrong ------------------------

def test_split_attributes_handles_quotes_nesting_and_escapes():
    assert SD.split_attributes("'a','b'") == ["'a'", "'b'"]
    # a comma inside a quoted string must not split
    assert SD.split_attributes("'Smith, John',$") == ["'Smith, John'", "$"]
    # SPF escapes a quote by doubling it; the naive reader ends the string early and mis-splits
    assert SD.split_attributes("'it''s',#4") == ["'it''s'", "#4"]
    # nested lists and constructed types stay one attribute
    assert SD.split_attributes("(#1,#2),IFCLABEL('x'),$") == ["(#1,#2)", "IFCLABEL('x')", "$"]
    # unbalanced input is reported, never silently accepted as one attribute
    assert SD.split_attributes("(#1,#2") is None
    assert SD.split_attributes("'unterminated") is None


def test_multi_line_instances_are_one_instance():
    """A representation spanning lines is completely ordinary; a line-based scan calls each truncated."""
    t = MINIMAL.replace("#2= IFCCARTESIANPOINT((0.,0.,0.));",
                        "#2= IFCCARTESIANPOINT(\n  (0.,\n   0.,\n   0.)\n);")
    r = SD.diagnose_text(t)
    assert r["instances"] == 2
    assert r["summary"]["error"] == 0, r["findings"]


def test_counts_stay_true_when_the_finding_list_is_capped():
    """`reported` may be capped; `error` may not.

    Summarising the truncated list would report the cap and read as a nearly-clean file — the exact
    shape of a payload cap that hides its own truncation.
    """
    n = SD.MAX_FINDINGS_PER_CODE + 25
    bad = "\n".join(f"#{i + 10}= IFCNOTATHING('x');" for i in range(n))
    r = SD.diagnose_text(MINIMAL.replace("#2= IFCCARTESIANPOINT((0.,0.,0.));", bad))
    assert r["summary"]["by_code"]["UNKNOWN_ENTITY"] == n
    assert r["summary"]["error"] >= n
    assert r["summary"]["truncated"] is True
    assert len(r["findings"]) < n


def test_findings_locate_the_fault_by_instance_id():
    """A diagnostic that says "something is wrong" is not actionable on a 1M-instance file."""
    t = MINIMAL.replace("#2= IFCCARTESIANPOINT((0.,0.,0.));", "#77= IFCNOTATHING('x');")
    f = SD.diagnose_text(t)["findings"][0]
    assert f["instance"] == 77
    assert f["entity"] == "IFCNOTATHING"


def test_detects_the_input_that_CRASHES_the_parser():
    """The fault that motivated the pre-flight screen in `ifc_loader`.

    ifcopenshell 0.8.5 **segfaults** on an IFC ending inside an unclosed `'` literal — exit 139,
    reproduced 3/3. That is not an exception, so no caller can catch it; the process dies.

    **This test does not call `ifcopenshell.open`.** Doing so would take the test runner down with it,
    and a suite that cannot survive its own fixture is not a suite. The crash is documented here and
    verified out of process; what is asserted in-process is that the detector fires.
    """
    t = MINIMAL.replace("'P'", "'P")
    r = SD.diagnose_text(t)
    assert r["passed"] is False
    assert "UNTERMINATED_STRING" in r["summary"]["by_code"]
    assert "SEGFAULT" in r["findings"][-1]["message"].upper()


def test_open_model_refuses_the_crashing_file_instead_of_dying():
    """`ifc_loader.open_model` must turn the crash into an ordinary error, at the choke point.

    `open_model` has 133 callers; screening there covers every path that reads a model, including
    uploads. Asserted through the real function, not the detector — a screen that is written but never
    wired is the shape this repo has shipped seven times.
    """
    from aec_data.ifc_loader import UnreadableIfc, open_model

    path = os.path.join(os.path.dirname(__file__), "test_storage_sd_trunc", "truncated.ifc")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(MINIMAL.replace("'P'", "'P"))
    try:
        raised = None
        try:
            open_model(path)
        except UnreadableIfc as e:
            raised = e
        assert raised is not None, "open_model accepted a file that segfaults the parser"
        assert "truncated" in str(raised).lower()
    finally:
        os.remove(path)
        os.rmdir(os.path.dirname(path))


def test_open_model_still_opens_the_files_it_always_did():
    """The other half, and the one a narrow screen exists to protect.

    An unclosed parenthesis and a mid-instance truncation both FAIL this module's structural checks and
    ifcopenshell opens them without complaint. If the screen were "refuse anything that does not parse",
    those would start failing — a worse bug than the crash, because it breaks working uploads.
    """
    from aec_data.ifc_loader import open_model

    p = os.path.join(SAMPLES, "rooms_demo.ifc")
    if os.path.exists(p):
        assert open_model(p) is not None

    path = os.path.join(os.path.dirname(__file__), "test_storage_sd_paren", "paren.ifc")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(MINIMAL.replace("#2= IFCCARTESIANPOINT((0.,0.,0.));", "#2= IFCCARTESIANPOINT((0.,0.,0.)"))
    try:
        # Structurally bad AND openable: exactly the case the screen must not touch.
        assert "UNPARSEABLE_INSTANCE" in SD.diagnose_file(path)["summary"]["by_code"]
        assert open_model(path) is not None
    finally:
        os.remove(path)
        os.rmdir(os.path.dirname(path))


def test_the_hot_path_screen_never_rejects_what_the_exact_reader_accepts():
    """The contract between the two readers is ONE-DIRECTIONAL, and that is deliberate.

    `scan_unterminated_string` is the hot-path screen (quote parity, then a confirm);
    `_text_ends_in_string` is the exact comment-aware reader. They are NOT required to agree, because
    the two ways of disagreeing are not equally harmful:

    - screen says **unterminated** while the exact reader says fine -> a valid model is REFUSED. This
      must never happen, and is what this test asserts.
    - screen says **fine** while the exact reader says unterminated -> the parser crashes on a file it
      was already crashing on before the screen existed. No regression, and it is the direction parity
      can fail in when a `/* … */` comment holds a stray apostrophe.

    Asserting plain equality here would be asserting the wrong contract, and would have to be weakened
    the first time a commented file turned up — a test that gets relaxed under pressure was measuring
    the wrong thing.
    """
    import shutil
    import tempfile

    cases = [
        "no quotes at all",
        "'closed'",
        "'unclosed",
        "'it''s closed'",
        "'it''s unclosed",
        "'a'" * 700,                          # crosses the chunk boundary many times
        "'" + "x" * (SD._CHUNK - 1) + "'",    # a closing quote as the first byte of chunk 2
        "'" + "x" * (SD._CHUNK - 1),          # opens in chunk 1, never closes
        "'a''" + "b" * SD._CHUNK + "'",       # an escaped quote landing on the boundary
        "/* it''s fine */'closed'",           # apostrophe escaped inside a comment
        "/* it's odd */'closed'",             # a LONE apostrophe in a comment: parity says odd
        "/* it's odd */'unclosed",            # the documented false-negative case
    ]
    d = tempfile.mkdtemp()
    tolerated = 0
    try:
        for i, text in enumerate(cases):
            p = os.path.join(d, f"c{i}.ifc")
            with open(p, "w", encoding="utf-8") as fh:
                fh.write(text)
            screen = SD.scan_unterminated_string(p)
            exact = SD._text_ends_in_string(text)
            assert not (screen and not exact), (
                f"case {i} would REFUSE A VALID FILE: screen={screen} exact={exact} for {text[:50]!r}")
            if exact and not screen:
                tolerated += 1
    finally:
        # rmtree, not rmdir: on Windows a just-closed handle can still be held briefly, and a cleanup
        # failure must not be reported as a failure of the thing under test.
        shutil.rmtree(d, ignore_errors=True)
    # The tolerated direction must be REACHED by this test, not merely allowed by it — otherwise the
    # assertion above is the only live one and the asymmetry is untested prose.
    assert tolerated == 1, f"expected exactly the one documented false negative, got {tolerated}"


def test_a_comment_with_an_apostrophe_is_not_refused():
    """The specific false positive the parity filter is designed to avoid.

    A lone `'` inside `/* … */` shifts quote parity, so the cheap filter calls the file suspicious. If
    odd parity decided on its own, this valid model would be refused. It escalates to the comment-aware
    confirm instead, which is the whole reason the filter is only trusted in one direction.
    """
    import shutil
    import tempfile

    d = tempfile.mkdtemp()
    try:
        p = os.path.join(d, "commented.ifc")
        with open(p, "w", encoding="utf-8") as fh:
            fh.write(MINIMAL.replace("DATA;", "DATA;\n/* exported by Bob's tool */"))
        assert SD.scan_unterminated_string(p) is False
    finally:
        shutil.rmtree(d, ignore_errors=True)


def test_the_engine_is_REACHABLE_over_http():
    """An engine with no route is indistinguishable from a working feature, from the outside.

    Seven of eleven things built across v0.3.701-710 shipped with no route. `test_reachable.py` is the
    gate for that, but it walks the import graph of **`aec_api`** and this engine lives in `aec_data`,
    so it is not covered there — and the route imports it lazily inside the handler, which a
    direct-reference check would not see either. So it is asserted here, over HTTP, with a started app.

    Both halves matter and they caught different things. Presence in the OpenAPI schema proved the route
    was *defined*; the request proved it was *callable*, and the first version was in the schema and
    raised `NameError` on every call — `source_ifc_path` is imported into that module as `_source_ifc`.
    A schema-only assertion would have shipped it.

    The status is compared against the SIBLING endpoints rather than pinned to a literal: what must be
    true is that this route is guarded exactly like the others, and a hard-coded 404 would keep passing
    if the whole family started returning 500.
    """
    from fastapi.testclient import TestClient

    from aec_api.main import app

    path = "/projects/{pid}/models/schema-diag"
    with TestClient(app) as c:
        assert path in app.openapi()["paths"], "route not served — nothing can call the engine"
        mine = c.get("/projects/no-such-project/models/schema-diag").status_code
        siblings = [c.get(f"/projects/no-such-project/models/{p}").status_code
                    for p in ("norm-valid", "qa")]
        assert mine < 500, f"schema-diag returned {mine} — the handler raised"
        assert all(mine == s for s in siblings), (
            f"schema-diag={mine} but siblings={siblings}; the guard differs from the family it joined")


if __name__ == "__main__":
    import sys
    fails = 0
    for name, fn in sorted(globals().items()):
        if not name.startswith("test_") or not callable(fn):
            continue
        try:
            fn()
            print(f"  ok   {name}")
        except Exception as e:  # noqa: BLE001 — a harness reports, it does not re-raise
            fails += 1
            print(f"  FAIL {name}: {type(e).__name__}: {e}")
    print(f"{'FAILED' if fails else 'PASSED'} — {fails} failure(s)")
    sys.exit(1 if fails else 0)
