"""Alembic drift guard: `alembic upgrade head` builds the current schema on a fresh empty DB, and
`alembic check` then reports NO model-vs-migration diff. This is the safety net that lets the additive
runtime path (create_all + _ensure_*) stay active while Alembic is the source of truth going forward —
if a model changes without a matching revision, `alembic check` fails here.

Runs on SQLite (like the rest of the gate); the Postgres-specific guard (FTS GIN indexes + a
create_all-vs-alembic schema diff) lives in .github/workflows/db-migrations.yml.
Run: cd services/api && PYTHONPATH=src DATABASE_URL=sqlite:///./_test_alembic_migrations.db python test_alembic_migrations.py
"""
import os
from pathlib import Path

os.environ.setdefault("DATABASE_URL", "sqlite:///./_test_alembic_migrations.db")
os.environ.setdefault("STORAGE_DIR", "./_storage_test_alembic_migrations")

HERE = Path(__file__).resolve().parent
# fresh EMPTY db so `upgrade head` actually CREATEs the schema (not a no-op against a create_all db)
_db = HERE / "_test_alembic_migrations.db"
_db.unlink(missing_ok=True)

from alembic import command  # noqa: E402
from alembic.config import Config  # noqa: E402
from alembic.util import AutogenerateDiffsDetected  # noqa: E402

cfg = Config(str(HERE / "alembic.ini"))
cfg.set_main_option("script_location", str(HERE / "migrations"))

# 1) fresh empty DB -> upgrade head must succeed and build the schema
command.upgrade(cfg, "head")

from sqlalchemy import create_engine, inspect  # noqa: E402

insp = inspect(create_engine(os.environ["DATABASE_URL"]))
tables = set(insp.get_table_names())
assert "alembic_version" in tables, "upgrade head did not stamp alembic_version"
assert "projects" in tables and "topics" in tables, f"baseline missing core tables: {sorted(tables)[:10]}"
assert any(t.startswith("mod_") for t in tables), "baseline missing dynamic mod_<key> module tables"
n_tables = len([t for t in tables if t != "alembic_version"])

# 2) models must match migrations — no pending autogenerate diff (the drift guard)
try:
    command.check(cfg)
except AutogenerateDiffsDetected as e:
    raise AssertionError(f"alembic check found model-vs-migration drift: {e}") from e

print(f"PASS  test_alembic_migrations  (upgrade head built {n_tables} tables; alembic check clean)")
