"""
A size budget on the files that are edited most.

This exists because of a question the user asked on 2026-07-28: is this codebase heading somewhere it
can no longer be worked on? The honest answer needed a measurement rather than a reassurance, and the
measurement found one file:

    api/client.ts   4,956 lines   152 commits/14d   631 methods on one class

Length alone is not the problem — `schema.d.ts` is 32k lines and nobody suffers, because it is
generated and nobody reads it. The problem is **length x churn**: a file that must be opened to add
any endpoint, is opened ~11 times a day, and only ever grows. Every change to it competes with every
other change for the same window of attention.

So the budget is not "files should be small". It is: **the files we edit constantly must stay small
enough to hold in your head at once.** Generated files and vendored copies are exempt by name, not by
size, because exemption-by-size is how a budget dies.

The threshold is deliberately set ABOVE today's worst offender. This test is a ratchet that stops the
problem getting worse while SCALE-SEAM brings it down; tightening the number is part of that work.
Setting it below the current state would have shipped a red test, and a red test that everyone learns
to ignore protects nothing.
"""
import os
import subprocess
import sys

FAILED = []


def check(label, ok, detail=""):
    print(f"{'PASS' if ok else 'FAIL'}  {label}" + (f"   {detail}" if detail else ""))
    if not ok:
        FAILED.append(label)


ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))

#: Hand-written source we own. A file over this is a file nobody can review in one sitting.
CEILING = 5_200

#: Per-file ceilings for the files SCALE-SEAM is actively splitting. **Only ever revised DOWN.**
#:
#: WHY THIS EXISTS, and it is a correction to how the ratchet was understood. `CEILING` above is a
#: single GLOBAL number, so it is pinned by whichever file is worst — today `viewer/app.ts` at 5,106
#: (5,064 when this was written; AUTH-SNAP-OVERRIDE added 42 lines the same day, which is exactly how
#: a number embedded in prose goes stale — the assertion below reads the file, this sentence does not).
#: That means an extraction out of any OTHER file cannot move it: SCALE-SEAM ⑦ took 96 lines out of
#: `client.ts` and the global ceiling was as true at 5,200 afterwards as before. The instruction
#: "lower the ceiling as each extraction lands" is right about the intent and cannot be carried out
#: by this number — lowering it to that figure would ratchet a slack belonging to `viewer/app.ts`, a file
#: in a different lane, and leave it with zero headroom so the next edit there fails the build.
#:
#: **A ratchet has to be per-subject when the work is per-subject.** One global number measures the
#: worst file and is silent about every other, which is the same shape as a gate whose scope is
#: narrower than its claim.
#:
#: A new endpoint added straight to `client.ts` will fail this, and that friction is the point rather
#: than a side effect: the question it forces is "should this live in a domain module instead?", and
#: post-⑦ the answer is usually yes. Raising an entry is therefore a deliberate act that should be
#: argued for in the commit message — the direction of travel is down.
PER_FILE = {
    "apps/web/src/api/client.ts": 3_796,   # SCALE-SEAM ⑧ (/proforma out); ⑦ 3,871; before ⑦ 3,967
}

#: Exempt because a human never reads them top-to-bottom. Name them, never infer them.
EXEMPT_SUBSTRINGS = (
    "/vendor/",           # vendored upstream copies — re-synced by overwrite, never hand-edited
    "schema.d.ts",        # generated from the OpenAPI schema
    "/node_modules/",
    "/dist/",
    "/.venv/",
    "package-lock.json",
    "demoData.json",      # a captured snapshot, regenerated by build_demo_data.py
    "/migrations/versions/",   # alembic autogenerate output; hand-editing one is already the bug
)


def tracked_source():
    """Files git knows about — not the working tree, so build output can never enter the budget."""
    out = subprocess.run(
        ["git", "ls-files", "*.py", "*.ts", "*.tsx", "*.js"],
        cwd=ROOT, capture_output=True, text=True, timeout=120,
    )
    for rel in out.stdout.splitlines():
        rel = rel.strip().replace("\\", "/")
        if not rel or any(s in "/" + rel for s in EXEMPT_SUBSTRINGS):
            continue
        path = os.path.join(ROOT, rel)
        try:
            with open(path, encoding="utf-8", errors="replace") as fh:
                yield rel, sum(1 for _ in fh)
        except OSError:
            continue


sizes = sorted(tracked_source(), key=lambda kv: -kv[1])
check("the source tree is readable at all", len(sizes) > 100, f"{len(sizes)} files measured")

over = [(rel, n) for rel, n in sizes if n > CEILING]
check(
    f"no hand-written file exceeds {CEILING} lines",
    not over,
    "; ".join(f"{rel}={n}" for rel, n in over[:5]) or "",
)

measured = dict(sizes)

# A per-file ratchet keyed by PATH silently stops ratcheting the moment the path changes — a rename,
# a move, or an exemption that starts matching would drop the entry and this check would go green by
# measuring nothing. So assert the subjects are present BEFORE asserting their sizes, individually
# rather than in aggregate: an aggregate non-empty check cannot see a dead entry beside a live one.
missing = [rel for rel in PER_FILE if rel not in measured]
check(
    "every per-file ratchet still names a file that exists",
    not missing,
    "; ".join(missing) or f"{len(PER_FILE)} tracked",
)

grew = [(rel, measured[rel], cap) for rel, cap in PER_FILE.items()
        if rel in measured and measured[rel] > cap]
check(
    "no file under an extraction ratchet has grown",
    not grew,
    "; ".join(f"{rel}={n} > {cap}" for rel, n, cap in grew)
    or "; ".join(f"{rel}={measured[rel]}/{cap}" for rel, cap in PER_FILE.items() if rel in measured),
)

# The ratchet only ratchets if somebody can see the headroom. Print the top of the list every run so
# a file approaching the ceiling is visible BEFORE it crosses and blocks somebody mid-sprint.
print("\n  largest hand-written files:")
for rel, n in sizes[:8]:
    room = CEILING - n
    flag = "  <-- at the ceiling" if room < 400 else ""
    print(f"    {n:>6}  {rel}{flag}")

# A budget nobody can act on is decoration. If the worst file is over the *target*, say what to do —
# the seam is the fix, and the roadmap item that owns it is named so this points somewhere real.
TARGET = 3_000
worst_rel, worst_n = sizes[0]
if worst_n > TARGET:
    print(
        f"\n  NOTE: {worst_rel} is {worst_n} lines, over the {TARGET}-line target.\n"
        f"        Roadmap SCALE-SEAM owns bringing this down by splitting along domain seams.\n"
        f"        Lower CEILING here as each extraction lands — that is what makes it a ratchet."
    )

print()
if FAILED:
    print("FAILED:", ", ".join(FAILED))
    sys.exit(1)
print("test_file_sizes OK")
