"""client_decisions (PORTAL-TXN)

Revision ID: a5601f75ba65
Revises: cf11784d84c6
Create Date: 2026-07-23 11:39:46.092708
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a5601f75ba65'
down_revision: str | None = 'cf11784d84c6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('item_ref', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_decisions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_decisions_token'), ['token'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_decisions_token'))
        batch_op.drop_index(batch_op.f('ix_client_decisions_project_id'))

    op.drop_table('client_decisions')
    # ### end Alembic commands ###
