"""mod_progress_actual (PROD-ACTUALS persistence)

Revision ID: 37bd38285a84
Revises: 832354473e90
Create Date: 2026-07-23 21:00:46.147312
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '37bd38285a84'
down_revision: str | None = '832354473e90'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mod_progress_actual',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('ref', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('workflow_state', sa.String(), nullable=True),
    sa.Column('party_owner', sa.String(), nullable=True),
    sa.Column('assignee', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anchor', sa.JSON(), nullable=True),
    sa.Column('element_guids', sa.JSON(), nullable=True),
    sa.Column('links', sa.JSON(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mod_progress_actual', schema=None) as batch_op:
        batch_op.create_index('ix_mod_progress_actual_proj_assignee', ['project_id', 'assignee'], unique=False)
        batch_op.create_index('ix_mod_progress_actual_proj_created', ['project_id', 'created_at'], unique=False)
        batch_op.create_index('ix_mod_progress_actual_proj_state', ['project_id', 'workflow_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_mod_progress_actual_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mod_progress_actual_workflow_state'), ['workflow_state'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mod_progress_actual', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mod_progress_actual_workflow_state'))
        batch_op.drop_index(batch_op.f('ix_mod_progress_actual_project_id'))
        batch_op.drop_index('ix_mod_progress_actual_proj_state')
        batch_op.drop_index('ix_mod_progress_actual_proj_created')
        batch_op.drop_index('ix_mod_progress_actual_proj_assignee')

    op.drop_table('mod_progress_actual')
    # ### end Alembic commands ###
