"""share_tokens.show_payments (PORTAL-TXN p2)

Revision ID: 33cd453413dd
Revises: a5601f75ba65
Create Date: 2026-07-23 15:50:04.282358
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '33cd453413dd'
down_revision: str | None = 'a5601f75ba65'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_payments', sa.Boolean(), nullable=False,
                                      server_default=sa.false()))   # existing tokens stay financials-off

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_tokens', schema=None) as batch_op:
        batch_op.drop_column('show_payments')

    # ### end Alembic commands ###
