"""stepup_spent: a step-up assertion is single-use

Revision ID: 0a5e4f34b867
Revises: b06f7bc8ba2f
Create Date: 2026-07-31 11:48:21.195464
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a5e4f34b867'
down_revision: str | None = 'b06f7bc8ba2f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stepup_spent',
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('sub', sa.String(), nullable=False),
    sa.Column('act', sa.String(), nullable=False),
    sa.Column('spent_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    with op.batch_alter_table('stepup_spent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stepup_spent_spent_at'), ['spent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stepup_spent_sub'), ['sub'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stepup_spent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stepup_spent_sub'))
        batch_op.drop_index(batch_op.f('ix_stepup_spent_spent_at'))

    op.drop_table('stepup_spent')
    # ### end Alembic commands ###
