"""professional_licenses seal identity binding

Backs the seal-identity fix. /pdf/seal previously took the seal name, licence number and state as a
caller-supplied form field, so an authenticated user could seal under anyone's licence and the audit
row recorded only what they typed. The seal text is now built server-side from a row here, written by
a platform admin (verified_by/verified_at) rather than self-served.

A table rather than columns on users: an engineer is routinely licensed in several states, each with
its own number and expiration.

Revision ID: b06f7bc8ba2f
Revises: b41f7c2ad8e6
Create Date: 2026-07-29 22:12:27.857019
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b06f7bc8ba2f'
down_revision: str | None = 'b41f7c2ad8e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professional_licenses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('name_on_seal', sa.String(), nullable=False),
    sa.Column('license_no', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('discipline', sa.String(), nullable=True),
    sa.Column('expiration', sa.String(), nullable=True),
    sa.Column('verified_by', sa.String(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('professional_licenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_professional_licenses_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_professional_licenses_user'), ['user'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_licenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_professional_licenses_user'))
        batch_op.drop_index(batch_op.f('ix_professional_licenses_state'))

    op.drop_table('professional_licenses')
    # ### end Alembic commands ###
